version: '3'

services:
  db:
    container_name: db
    restart: always
    image: postgres:11
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: driblo
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    networks:
      - network-api
    # volumes:
    #   - ./dados:/var/lib/postgresql/data
  web:
    container_name: web
    image: api
    depends_on:
      - db
    command: bash -c "npx sequelize db:migrate && yarn dev"
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8002:8002'
    networks:
      - network-api
networks:
  network-api:
    external:
      name: network-api