version: '3'

services:
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: driblo
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    networks:
      - api-backend
  web:
    container_name: web
    depends_on:
      - db
    command:  bash -c "yarn && yarn sequelize db:migrate && yarn dev"
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8002:8002'
    networks:
      - api-backend
networks:
  api-backend:
    external:
      name: api-backend
